services:
  - type: web
    name: paircanvas-signalling-server
    runtime: docker
    dockerfilePath: ./Dockerfile.render
    plan: free
    envVars:
      - key: PORT
        value: 8080
    healthCheckPath: /health
